# Generated by Django 2.0.2 on 2018-03-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AfterEvent',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('id_user', models.IntegerField()),
                ('imperessions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'after_event',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(blank=True, max_length=45, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=60, null=True)),
                ('desctiption', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('rating_plus', models.IntegerField(blank=True, null=True)),
                ('rating_minus', models.IntegerField(blank=True, null=True)),
                ('rating_zero', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='EventUsers',
            fields=[
                ('id_event', models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.Events')),
                ('status', models.TextField(blank=True, null=True)),
                ('organizer', models.IntegerField(blank=True, null=True)),
                ('initializer', models.IntegerField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='api.Users')),
            ],
            options={
                'db_table': 'event_users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='afterevent',
            unique_together={('id_event', 'id_user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventusers',
            unique_together={('id_event', 'id_user')},
        ),
    ]
