# Generated by Django 2.0.2 on 2018-03-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='tegs',
            new_name='tags',
        ),
    ]
