# Generated by Django 2.0.2 on 2018-03-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventusers',
            name='id_event',
            field=models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='eventusers', serialize=False, to='api.Events'),
        ),
    ]
